name: Console Log Guard
on: [workflow_call]

jobs:
  consoleLogGuard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Count total console logs and set env
        run: echo "TOTAL_CONSOLE_LOGS=$(git diff  ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep console.log\( | wc -l)" >> $GITHUB_ENV

      - name: Test
        run: |
          if [[ ${{env.TOTAL_CONSOLE_LOGS}} > 0 ]]; then
            echo "STOP! You violated the law!"
            echo "Detected ${{env.TOTAL_CONSOLE_LOGS}} console.logs in this pull request"
            echo "Please remove all console.logs"
            exit 42
          else
            echo "Nothing to see here. Move along."
          fi
