on:
  pull_request:
    types: [opened, reopened, synchronize, closed, ready_for_review]


jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #   lines: ${{ steps.changes.outputs.lines }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo BASE SHA ${{ github.event.pull_request.base.sha }}
      - run: echo GH SHA ${{ github.sha }}
      # - run: echo $${{git diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }}
      # WORKS
      # - run: echo "FOO=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep console.log\( | wc -l)"
      - name: total console logs
        env: 
          FOO: echo ${{ $(git diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep console.log\( | wc -l ) }}
        run: echo "$FOO"
      # - run: echo "${{ env.FOO }}"
      # - name: Get changed files
      #   id: changes
      #   # Set outputs using the command.
      #   run: |
      #     echo "::set-output name=lines::$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.sha }})"
  # lint:
  #   runs-on: ubuntu-latest
  #   # require the first job to have ran
  #   needs: changedfiles
  #   # only run there are changed files
  #   steps:
  #     - name: echo changed files
  #       run: echo ${{needs.changedfiles.outputs.lines}}
